spotKeys:
  publicKey: "__your_spotify_client_id__"
  secretKey: "__your_spotify_secret__"

server:
  image: yooooomi/your_spotify_server
  tag: 1.11.0
  pullPolicy: IfNotPresent
  port: 8080
  mongoEndpoint: "localhost:27017"

mongo:
  image: mongo:6
  pullPolicy: IfNotPresent
  dbStorage:
    hostPath: /

web:
  image: yooooomi/your_spotify_client
  tag: 1.11.0
  pullPolicy: IfNotPresent
  port: 3000

runAs:
  user: 568
  group: 568
