endpoints:
  apiEndpoint: "http://localhost:8080"
  clientEndpoint: "http://localhost:3000"

spotKeys:
  publicKey: "__your_spotify_client_id__"
  scretKey: "__your_spotify_secret__"

server:
  image: yooooomi/your_spotify_server
  tag: 1.11.0
  pullPolicy: IfNotPresent
  port: 8080

mongo:
  image: mongo:6
  pullPolicy: IfNotPresent
  useHostPath: false # If true use hostPath, if false use PVC
  hostPath: / # Path to use if hostPath is true
  storageSize: 1Gi # PVC storage size if useHostPath is false

web:
  image: yooooomi/your_spotify_client
  tag: 1.11.0
  pullPolicy: IfNotPresent
  port: 3000

runAs:
  user: 568
  group: 568
