apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: {{ .Values.server.port }}
  selector:
    app: {{ .Release.Name }}-server
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: {{ .Values.web.port }}
  selector:
    app: {{ .Release.Name }}-web
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: {{ .Release.Name }}-mongo
